### ISSUE TITLE
virtualbox compiled version

### ISSUE THREAD

**Issue by tiankangbo2019** [zrax/libvbox#4]
Hello, zrax, I found that your project is not compatible with the compiled version of VirtualBox after testing. In the compiled version, "auto vboxclient = VBox:: virtualboxclient()" is a failure. Can you change this situation?

**Comment by zrax** [comment]
What do you mean by "the compiled version of VirtualBox"?  If you mean that you built VirtualBox from source, you will need to use the SDK associated with that build.  Also, note that if you're building directly from SVN, there may be API changes in the COM interface that aren't reflected by libvbox's wrappers, since I only formally support released versions of VirtualBox.

**Comment by tiankangbo2019** [comment]
Thank you for your answer. I see
